services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mypwd
      MYSQL_DATABASE: demodb
    ports:
      - "4306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./products-api
    container_name: spring-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./products-app
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
